---

- name: Make the directory where tenant site code will be stored (if it doesn't already exist)
  file:
    path: /data/site_code/
    owner: awx
    group: awx
    state: directory
    mode: 0770
  run_once: yes
  become: no


- name: Git Repo clone if deploying to testint
#Needs to be set since it tries to exec things in /tmp, which is not allowed based on security settings in /etc/fstab
  environment:
    TMPDIR: "/data/site_code/tmp"
  git:
    accept_hostkey: yes
    repo: '{{ base_stash_project }}{{ tenant_repo }}'
    dest: '{{ local_repo }}'
    version: "develop"
    track_submodules: yes
    force: yes
    depth: 1
  become: no
  when: env == "testint"
  run_once: yes


- name: Update the Submodule (if the submodule code is in the server for testint)
  shell: "cd {{ submodule_path }} && {{ item }}"
  when: env == "testint"
  become: no
  with_items:
    - git checkout develop
    - git reset --hard origin/develop
  run_once: yes


 
- name: Git Repo clone if deploying to staging
#Needs to be set since it tries to exec things in /tmp, which is not allowed based on security settings in /etc/fstab
  environment:
    TMPDIR: "/home/bamboo/tmp"
  git:
    accept_hostkey: yes
    repo: '{{ base_stash_project }}{{ tenant_repo }}'
    dest: '{{ local_repo }}'
    version: "master"
    track_submodules: yes
    force: yes
    depth: 1
  become: no
  when: env == "staging"
  run_once: yes


- name: Update the Submodule (if the submodule code is in the server for staging)
  shell: "cd {{ submodule_path }} && {{ item }}"
  when: env == "master"
  become: no
  with_items:
    - git checkout master
    - git reset --hard origin/master
  run_once: yes



- name: Git Repo clone if deploying to prod
#Needs to be set since it tries to exec things in /tmp, which is not allowed based on security settings in /etc/fstab
  environment:
    TMPDIR: "/home/bamboo/tmp"
  git:
    accept_hostkey: yes
    repo: '{{ base_stash_project }}{{ tenant_repo }}'
    dest: '{{ local_repo }}'
    version: "live"
    track_submodules: yes
    force: yes
    depth: 1  
  become: no
  when: env == "production"
  run_once: yes


- name: Update the Submodule (if the submodule code is in the server for prod)
  shell: "cd {{ submodule_path }} && {{ item }}"
  when: env == "production"
  become: no
  with_items:
    - git checkout live
    - git reset --hard origin/live
  run_once: yes



- name: Git Settings
  environment:
    TMPDIR: "/home/bamboo/tmp"
  git:
    repo: '{{ base_stash_project }}{{ tenant_settings }}'
    dest: '{{ local_settings }}'
    version: "master"
    update: yes
    force: yes 
  become: no
  run_once: yes
  ignore_errors: yes

