---
- name: Create Initial Directories regardless of what is run
  block:
    - name: Set Docking Path
      set_fact:
        aws_docking_path: "/data/adhoc_tasks/{{ site_alias }}_files"
        netstorage_path: "{{ akamai_path }}"
        target_site_alias: "{{ site_alias }}"
        path_type: ""
        path_stats: []
        

    - name: Set Target Site Alias when Different
      set_fact:
        target_site_alias: "{{ related_alias }}"
      when:
        - target_env is defined
        - target_env != "netstorage"
        - target_site is defined
        - target_site == "alternative"

    - name: Set Paths
      set_fact:
        aws_docking_assets: "/data/adhoc_tasks/{{ site_alias }}_files/asset_files/files"
        aws_db_path: "/data/adhoc_tasks/{{ site_alias }}_files/database_files"
        netstorage_asset_tar_path: "/data/adhoc_tasks/{{ target_site_alias }}_files/adhoc_files/asset_files"
        target_asset_backup_path: "/data/adhoc_tasks/{{ target_site_alias }}_files/adhoc_files/asset_files"
        netstorage_db_tar_path: "/data/adhoc_tasks/{{ target_site_alias }}_files/adhoc_files/database_files"
        target_db_backup_path: "/data/adhoc_tasks/{{ target_site_alias }}_files/adhoc_files/database_files"
        netstorage_config_tar_path: "/data/adhoc_tasks/{{ target_site_alias }}_files/adhoc_files/config_exports"

    - name: Set Akamai Paths
      set_fact:
        akamai_asset_path: "{{ akamai_path }}/adhoc_files/{{ target_site_alias }}_files/asset_files"
        akamai_db_path: "{{ akamai_path }}/adhoc_files/{{ target_site_alias }}_files/database_files"
        akamai_config_path: "{{ akamai_path }}/adhoc_files/{{ target_site_alias }}_files/configs_exports"
        
    - name: Set Paths list for creation
      set_fact:
        create_list:
          - "{{ aws_docking_path }}/"
          - "{{ aws_docking_assets }}/"
          - "{{ aws_db_path }}/"
          - "{{ netstorage_asset_tar_path }}/"
          - "{{ netstorage_db_tar_path }}/"
          - "{{ netstorage_config_tar_path }}/"
          

    - name: Get Docking Path Stats
      stat:
        path: "{{ aws_docking_path }}/"
      register: aws_docking_stat


    - name: Set Creation Flag
      set_fact:
        path_type: "initial_creation"
      when: aws_docking_stat.stat.isdir is not defined


    - name: Make All Adhoc plan paths Related to a site
      file:
        path: "{{ item }}"
        state: directory
        owner: ansible_tower
        group: ansible_tower
        mode: 0776
        recurse: yes
      with_items: "{{ create_list }}"
      when: path_type == "initial_creation"

    - name: Get Docking Assests
      stat:
        path: "{{ aws_docking_assets }}/"
      register: aws_docasset_stat
      when: path_type != "initial_creation"

    - name: Make Docking Assests
      file:
        path: "{{ aws_docking_assets }}/"
        state: directory
        owner: apache
        group: apache
        mode: 0776
        recurse: yes
      when: 
        - aws_docasset_stat.stat.isdir is not defined
        - path_type != "initial_creation"


    - name: Make Asset Tar Path
      file:
        path: "{{ netstorage_asset_tar_path }}/"
        state: directory
        owner: ansible_tower
        group: ansible_tower
        mode: 0776
        recurse: yes
      when: 
        - aws_asset_tar_stat.stat.isdir is not defined
        - path_type != "initial_creation"

    - name: Get Docking db
      stat:
        path: "{{ aws_db_path }}/"
      register: aws_docdb_stat

    - name: Make Docking db
      file:
        path: "{{ aws_db_path }}/"
        state: directory
        owner: ansible_tower
        group: ansible_tower
        mode: 0776
        recurse: yes
      when: 
        - aws_docdb_stat.stat.isdir is not defined
        - path_type != "initial_creation"

    - name: Get Asset Tar Path
      stat:
        path: "{{ netstorage_asset_tar_path }}/"
      register: aws_asset_tar_stat

    - name: Get DB Tar Path
      stat:
        path: "{{ netstorage_db_tar_path }}/"
      register: aws_db_tar_stat

    - name: Make DB Tar Path
      file:
        path: "{{ netstorage_db_tar_path }}/"
        state: directory
        owner: ansible_tower
        group: ansible_tower
        mode: 0776
        recurse: yes
      when: 
        - aws_db_tar_stat.stat.isdir is not defined
        - path_type != "initial_creation"

    - name: Get Config path
      stat:
        path: "{{ netstorage_config_tar_path }}/"
      register: aws_config_stat
    
    - name: Make Config path
      file:
        path: "{{ netstorage_config_tar_path }}/"
        state: directory
        owner: ansible_tower
        group: ansible_tower
        mode: 0776
        recurse: yes
      when: 
        - aws_config_stat.stat.isdir is not defined
        - path_type != "initial_creation"

    - name: Change owner and group for Asset specific Paths
      file:
        path: "{{ item }}"
        owner: apache
        group: apache
        mode: 0776
        recurse: yes
      with_items: 
        - "{{ aws_docking_assets }}/"
        - "{{ netstorage_asset_tar_path }}/"
        - path_type == "initial_creation"
    
    - name: Set Asset Paths to Path list for clean up
      set_fact:
        asset_path_list:
          - "{{ aws_docking_assets }}/"
          - "{{ netstorage_asset_tar_path }}/"

    - name: Set DB Paths to list for clean up
      set_fact:
        db_path_list:
          - "{{ aws_db_path }}/"
          - "{{ netstorage_db_tar_path }}/"

    - name: Set Config Exports Paths to list for clean up
      set_fact:
        config_path_list:
          - "{{ netstorage_config_tar_path }}/"

- name: Create and Sync paths to Akamai if initial run
  block:
    - name: Set Temp Akamai Paths
      set_fact:
        akamai_temp_sync: "/data/adhoc_tasks/akamai_temp/adhoc_files"
        akamai_temp_db: "/data/adhoc_tasks/akamai_temp/adhoc_files/{{ target_site_alias }}_files/database_files"
        akamai_temp_assets: "/data/adhoc_tasks/akamai_temp/adhoc_files/{{ target_site_alias }}_files/asset_files"
        akamai_temp_config: "/data/adhoc_tasks/akamai_temp/adhoc_files/{{ target_site_alias }}_files/configs_exports"

    - name: Make a Temp directory to rsync over to netstorage
      file:
        path: "{{ akamai_temp_db }}/"
        state: directory
        owner: ansible_tower
        group: ansible_tower
        mode: 0776
        recurse: yes
      with_items:
        - "{{ akamai_temp_sync }}"
        - "{{ akamai_temp_db }}"
        - "{{ akamai_temp_config }}"

    - name: Make a Temp directory for apache to rsync over to netstorage
      file:
        path: "{{ item }}"
        state: directory
        owner: apache
        group: apache
        mode: 0776
        recurse: yes
      with_items:
        - "{{ akamai_temp_assets }}"


    - name: Sync Paths to Netstorage
      shell: "rsync -avz -e 'ssh -i /home/ansible_tower/.ssh/bamboo_idrsa -o HostKeyAlgorithms=+ssh-dss' {{ akamai_temp_sync }} sshacs@dhswcms.upload.akamai.com:{{ akamai_path }}"
    
    - name: Remove the Akamai Temp Path
      file:
        path: "/data/adhoc_tasks/akamai_temp"
        state: absent
      become: yes

  when: path_type == "initial_creation"
