---

- name: Create var with the timestamp
  command: "date +%m-%d-%Y-%H%M"
  register: git_tag_name

- name: Clone into compiled code directory for production
  environment:
    TMPDIR: "/data/site_code/tmp"
    PATH: "{{ ansible_env.PATH }}:/opt/rh/rh-git29/root/usr/bin:/opt/rh/httpd24/root/usr/lib64"
    LD_LIBRARY_PATH: "/opt/rh/httpd24/root/usr/lib64"

  git:
    accept_hostkey: yes
    executable: "{{ git_binary_path }}"
    repo: '{{ aws_stash_project }}'
    dest: '{{ local_checkouts }}{{ tenant }}/combined_code/{{ env }}'
    version: "live"
    force: yes
    depth: 1
    umask: "007"
  become: yes
  become_user: awx
  run_once: yes

- name: Remove old docroot directory in combined repos since it messes up mv later
  file:
    path: '{{ local_checkouts }}{{ tenant }}/combined_code/{{ env }}/docroot'
    state: absent
  run_once: yes

# Production Code Refactored
- name: Git Repo clone if repo is empty
#Needs to be set since it tries to exec things in /tmp, which is not allowed based on security settings in /etc/fstab
  environment:
    TMPDIR: "/home/bamboo/tmp"
    PATH: "{{ ansible_env.PATH }}:/opt/rh/rh-git29/root/usr/bin:/opt/rh/httpd24/root/usr/lib64"
    LD_LIBRARY_PATH: "/opt/rh/httpd24/root/usr/lib64"

  git:
    accept_hostkey: yes
    executable: "{{ git_binary_path }}"
    repo: '{{ base_stash_project }}{{ tenant_repo }}'
    dest: '{{ local_repo }}'
    version: "security"
    track_submodules: yes
    force: yes
#    depth: 1  
    umask: "007"
  become: yes
  become_user: awx
  run_once: yes

- name: Update the Submodule
  shell: "cd {{ submodule_path }} && {{ item }}"
  become: yes
  become_user: awx
  with_items:
    - git fetch --all
    - git checkout security
    - git reset --hard origin/security
  run_once: yes

- name: Git checkout live
  shell: "cd {{ local_repo }} && {{ item }}"
  become: yes
  become_user: awx
  with_items:
    - git checkout live
    - git reset --hard origin/live
  run_once: yes

- name: Git checkout live submodule
  shell: "cd {{ submodule_path }} && {{ item }}"
  become: yes
  become_user: awx
  with_items:
    - git checkout live
    - git reset --hard origin/live
  when: env == "production"
  run_once: yes

- name: Merge security to live
  shell: "cd {{ local_repo }} && {{ item }}"
  become: yes
  become_user: awx
  with_items:
    - git merge security
    - "git tag {{ git_tag_name.stdout }}"
    - "git push origin live {{ git_tag_name.stdout }}"
  when: env == "production"
  run_once: yes

- name: Merge security to live submodule
  shell: "cd {{ submodule_path }} && {{ item }}"
  become: yes
  become_user: awx
  with_items:
    - git merge security
    - "git tag {{ git_tag_name.stdout }}"
    - "git push origin live {{ git_tag_name.stdout }}"
  when: env == "production"
  run_once: yes

- name: Git Settings
  environment:
    TMPDIR: "/home/bamboo/tmp"
    PATH: "{{ ansible_env.PATH }}:/opt/rh/rh-git29/root/usr/bin:/opt/rh/httpd24/root/usr/lib64"
    LD_LIBRARY_PATH: "/opt/rh/httpd24/root/usr/lib64"

  git:
    repo: '{{ base_stash_project }}{{ tenant_settings }}'
    executable: "{{ git_binary_path }}"
    dest: '{{ local_settings }}'
    version: "master"
    update: yes
    force: yes
    umask: "007"
  become: yes
  become_user: awx
  run_once: yes
#  ignore_errors: yes

- name: Copy settings into sites/default
  copy:
    src: '{{ local_settings }}{{ env }}/'
    dest: "{{ local_repo }}/docroot/sites/default/"
    owner: awx
    group: awx
    mode: '0700'
  run_once: yes

- name: check if drush.yml exist in settings
  stat:
    path: '{{ local_repo }}/docroot/sites/default/drush.yml'
  register: drush_yml_file

- name: Creates directory for drush.yml file
  file:
    path: '{{ local_repo }}/docroot/sites/all/drush'
    state: directory
  when: drush_yml_file.stat.exists

- name: copy drush.yml
  copy:
    src: '{{ local_repo }}/docroot/sites/default/drush.yml'
    dest: '{{ local_repo }}/docroot/sites/all/drush/'
    owner: awx
    group: awx
    mode: '0700'
  when: drush_yml_file.stat.exists

# check if multisite
- name: check the location of sites.php file
  stat:
    path: "{{ local_settings }}multisite/sites.php"
  register: sites_file

- name: git_repo_and_settings.yml - set multisite fact if multisite is TRUE
  set_fact:
    multisite: True
  when: sites_file.stat.exists == True

- name: git_repo_and_settings.yml - set multisite fact if multisite is FALSE
  set_fact:
    multisite: False
  when: sites_file.stat.exists == False


- name: Create symlink to site-files
  file:
    src: '{{ sitefiles_root }}{{ env }}.{{ tenant }}_gov_build/files'
    dest: '{{ local_repo }}docroot/sites/default/files'
    state: link
    group: apache
    owner: apache
    force: yes
    follow: no
  run_once: yes

- name: Bypassing Ansible slowness tax with mv because Ansible module is painfully slow
  command: "cp -Rp {{ local_repo }}docroot {{ local_checkouts }}{{ tenant }}/combined_code/{{ env }}/"
  become: yes
  run_once: yes

- name: Remove .git directory in profile because it messes up our git push later
  file:
    path: "{{ local_checkouts }}{{ tenant }}/combined_code/{{ env }}/docroot/profiles/{{ tenant }}_gov/.git"
    state: absent
  run_once: yes

