---   
- name: Show Variables 
  debug:
    msg: "Running Directory Setup Web: Host: {{ inventory_hostname }} - {{ host_ip }} Environment: {{ env }} Site Alias: {{ tenant }}"

- name: Get wwwroot path
  stat:
    path: "{{ wwwroot_path }}"
  register: docroot_path

- name: Clone the combo repo
  git:
    accept_hostkey: yes
    repo: "https://maestro.dhs.gov/stash/scm/wcmaws/{{ combo_repo }}.git"
    dest: "{{ wwwroot_path }}"
    version: "{{ clone_branch }}"
    force: yes
    umask: "007"
  become: yes
  become_user: apache
  when: docroot_path.stat.isdir is not defined

- name: Change file ownership, group and permissions
  file:
    path: "{{ wwwroot_path }}/"
    owner: apache
    group: apache
    mode: '0770'
    recurse: yes
    follow: no
  become: yes
  become_user: root
  when: docroot_path.stat.isdir is not defined
  
- name: Set the config on first server in group
  shell: "cd {{ wwwroot_path }} && {{ item }}"
  with_items:
    - git config core.fileMode false
    - git commit --allow-empty -m "Updating git config filemode"
    - git push origin {{ clone_branch }}
  #loop_control:
  #  loop_var: git_command
  become: yes
  become_user: apache
  when: 
    - docroot_path.stat.isdir is not defined
    - host_ip == delegate_host
    # - clone_branch != "master"

- name: Git Check if we are on the correct branch
  shell: "cd {{ wwwroot_path }} && git name-rev --name-only HEAD"
  become: yes
  become_user: apache
  register: git_combo_branch_name
  when: docroot_path.stat.isdir is defined

- name: Show git branch
  debug:
    msg: "{{ git_combo_branch_name.stdout }}"
  when: docroot_path.stat.isdir is defined

- name: Check the git config
  shell: "cd {{ wwwroot_path }} && cat .git/config"
  register: git_config_out



