---
- name: Run stuff on tower
  block:
    - name: Create files directory in sites-files
      file:
        path: "{{ asset_path }}/files"
        owner: apache
        group: apache
        mode: 0770
        state: directory
      when: files_path.stat.isdir is not defined

    - name: Create files/tmp directory
      file:
        path: "{{ asset_path }}/tmp"
        mode: 0700
        owner: apache
        group: apache
        state: directory
      when: temp_path.stat.isdir is not defined

    - name: Create files/private directory
      file:
        path: "{{ asset_path }}/private"
        mode: 0700
        owner: apache
        group: apache
        state: directory
      when: private_path.stat.isdir is not defined

- name: Push the settings updates to branch
  block:
    - name: Push settings code to branch
      shell: "cd {{ settings_onboard }} && {{ item }}"
      become: yes
      become_user: awx
      with_items:
        - git add -A
        - git commit -m "Updating drush.yml for {{ tenant }} {{ env }}"
        - git push origin master
  when: vars_flag == "update"