---
#- name: Print Values
#  debug:
#    msg: "{{ site_alias }}"
#    msg: "{{ drupal_version }}"
#    msg: "{{ env }}"
#    msg: "{{ docroot_prefix }}"

#- name: Get the list of email users
#  script: roles/common/files/get_jira_users.py "{{ site_alias }}" "{{ drupal_version }}"
#  register: email_list
#  delegate_to: localhost
#  connection: local
#  become: no

- name: Remove the previous YAML for the update module (D8 only).
  command: /usr/bin/sudo su - apache -c "/usr/local/bin/drush --alias-path=/data/bamboo_scripts/drush_aliases -y --root={{ docroot }} pm-uninstall update"
  #delegate_to: "{{ web_server_drush }}"
  ignore_errors: yes


- name: Remove the previous settings for the update module (D8 only).
  command: /usr/bin/sudo su - apache -c "/usr/local/bin/drush --alias-path=/data/bamboo_scripts/drush_aliases -y --root={{ docroot }} cdel update.settings -y"
  #delegate_to: "{{ web_server_drush }}"
  ignore_errors: yes


- name: Enable the update, and wcm_tools modules (D8 only - for security checking)
  command: /usr/bin/sudo su - apache -c "/usr/local/bin/drush --alias-path=/data/bamboo_scripts/drush_aliases --root={{ docroot }} en {{ item }} -y"
  #delegate_to: "{{ web_server_drush }}"
  with_items:
    - update
    - wcm_tools
  ignore_errors: yes


- name: D8 - Set the update module to only check for Security updates (Rather than all updates)
  command: /usr/bin/sudo su - apache -c "/usr/local/bin/drush --alias-path=/data/bamboo_scripts/drush_aliases -y --root={{ docroot }} cset update.settings {{ item }}"
  with_items:
    - notification.threshold security
  #delegate_to: "{{ web_server_drush }}"
  ignore_errors: yes


- name: Drupal 8 emails
  command: "sudo -u apache /usr/local/bin/drush --alias-path=/data/bamboo_scripts/drush_aliases --root=/var/www/html/wwwroot/staging.{{ site_alias }}_gov_build/docroot cset -y update.settings notification.emails.{{ item }}"
  with_items:
    - "{{ email_list.stdout_lines }}"
  #delegate_to: "{{ web_server_drush }}"
  ignore_errors: yes

