- hosts: testint
  
  remote_user: bamboo
  become: yes 
  become_method: sudo

  tasks:
  - name: Copy httpd.conf
    copy: 
       src= ../files/httpd.conf 
       dest=/etc/httpd/conf/httpd.conf 
       owner=root 
       group=root 
       mode=0644
