---
- name: Set netstorage source path 
  set_fact:
    netstorage_source: "{{ akamai_path }}/refresh_files/{{ site_alias }}/database/*"
    target_db_file: "{{ target_env }}.{{ target_db_name }}_{{ current_run_timestamp.stdout }}"

- name: Sync File from NetStorage
  shell: "rsync -av -e 'ssh -i /home/bamboo/.ssh/id_rsa2 -p 8002' sshacs@172.22.84.11:{{ netstorage_source }} {{ db_refresh_path }}"
  become: no
  when: netstorage_source_flag == 1

- name: Get SQL File Name
  shell: "ls {{ db_refresh_path }}"
  register: sql_source_file
  when: netstorage_source_flag == 1

- name: Gunzip Database Backup
  command: "gunzip -f {{ db_refresh_path }}{{ sql_source_file.stdout }}"
  when: netstorage_source_flag == 1

- name: Get SQL FIle Name
  shell: "ls {{ db_refresh_path }}"
  register: gunzip_file_name
  when: netstorage_source_flag == 1

- name: Set SQL file as Fact
  set_fact:
    source_db_file: "{{ gunzip_file_name.stdout }}"
    from_netstorage_file: "{{ sql_source_file.stdout }}"
  when: netstorage_source_flag == 1

- name: Change the group and owner to bamboo
  file:
    path: "{{ db_refresh_path }}{{ source_db_file }}"
    owner: bamboo
    group: bamboo
    mode: 0770
  when: netstorage_source_flag == 1
  
- name: set wsrep_desync to one
  mysql_variables:
    variable: wsrep_desync
    value: 1
    login_host: "{{ target_db_ip }}"
    login_password: "{{ db_pass }}"
    login_user: "{{ db_user }}"
  when: target_env == "production" or target_env == "staging"
  ignore_errors: true
  
- name: Back up Target Database
  mysql_db:
    name: "{{ target_db_name }}"
    state: dump
    single_transaction: yes
    target: "{{ db_refresh_path }}{{ target_db_file }}.sql"
    login_host: "{{ target_db_ip }}"
    login_password: "{{ db_pass }}"
    login_user: "{{ db_user }}"

- name: Rename File for Backup and Email
  shell: "mv {{ db_refresh_path }}{{ target_db_file }}.sql {{ db_refresh_path }}{{ site_alias}}_{{ target_env }}_db_backup-{{ current_run_timestamp.stdout }}.sql"


- name: GZip sql target file
  shell: "gzip {{ db_refresh_path }}{{ site_alias}}_{{ target_env }}_db_backup-{{ current_run_timestamp.stdout }}.sql"
  register: sql_target_final
  
- name: Set target file name
  set_fact:
    target_netstorage_file: "{{ site_alias}}_{{ target_env }}_db_backup-{{ current_run_timestamp.stdout }}.sql.gz"


- name: Change owner and group to bamboo
  file:
    path: "{{ db_refresh_path }}{{ target_netstorage_file }}"
    owner: bamboo
    group: bamboo
    mode: 0770

- name: set wsrep_desync to zero
  mysql_variables:
    variable: wsrep_desync
    value: 0
    login_host: "{{ target_db_ip }}"
    login_password: "{{ db_pass }}"
    login_user: "{{ db_user }}"
  when: target_env == "production" or target_env == "staging"
  ignore_errors: true
  tags: skip


- name: Drop Target Database
  mysql_db:
    name: "{{ target_db_name }}"
    state: absent
    login_host: "{{ target_db_ip }}"
    login_password: "{{ db_pass }}"
    login_user: "{{ db_user }}"


- name: Re-Create Target Database
  mysql_db:
    name: "{{ target_db_name }}"
    state: present
    login_host: "{{ target_db_ip }}"
    login_password: "{{ db_pass }}"
    login_user: "{{ db_user }}"

- name: Import Source DB
  mysql_db:
    name: "{{ target_db_name }}"
    state: import
    target: "{{ db_refresh_path }}{{ source_db_file }}"
    login_host: "{{ target_db_ip }}"
    login_password: "{{ db_pass }}"
    login_user: "{{ db_user }}"

- name: Sync SQL target backup File to Netstorage
  shell: "rsync -av -e 'ssh -i /home/bamboo/.ssh/id_rsa2 -p 8002' {{ db_refresh_path }}{{ target_netstorage_file }} sshacs@172.22.84.11:{{ akamai_path }}" 
  become: no
  when: target_backup == "yes"
