---
- name: Run Drush for D7
  block:
    - name: Set Docroot paths Lower Environments
      set_fact:
        docroot_path: "/var/www/html/wwwroot/{{ target_env }}.{{ tenant }}_gov_build/docroot/"
      when: target_env == "testint" or target_env == "staging"

    - name: Set Docroot paths Upper Environments
      set_fact:
        docroot_path: "/var/www/html/wwwroot/{{ tenant }}_gov_build/docroot/"
      when: target_env == "prod"

    - name: Set Fact
      set_fact:
        delegate_host: "{{ item }}"
      with_inventory_hostnames:
        - "tag_purpose_{{ target_env }}"

    - name: Show Host
      debug:
        msg: "{{ delegate_host }}"

    - name: Run Drush updb (D7)
      command: /usr/bin/sudo su - apache -c "/usr/local/bin/drush --root={{ docroot_path }} updb -y"
    #  command: /usr/local/bin/drush --alias-path=/data/aws_scripts/drush_aliases @{{ tenant }}.{{ target_env }} updb -y 
      delegate_to: "{{ delegate_host }}"
      register: drush7_updb_result
      retries: 2
      until: drush7_updb_result.rc == 0
      ignore_errors: yes

    - name: Output of Drush updb (D7)
      debug:
        var: drush7_updb_result

    - name: Run Drush RR if Drupal 7
      command: /usr/bin/sudo su - apache -c "/usr/local/bin/drush --root={{ docroot_path }} rr"
    # command: /usr/local/bin/drush --alias-path=/data/aws_scripts/drush_aliases @{{ tenant }}.{{ target_env }} rr 
      delegate_to: "{{ delegate_host }}" 
      register: drush_rr_result
      retries: 0
     #until: drush_rr_result.rc == 0

    - name: Output of Drush RR
      debug:
        var: drush_rr_result
  rescue:
    - name: Get the Drupal version of the site, run drush dl registry_rebuild for D&
      command: /usr/bin/sudo su - apache -c "/usr/local/bin/drush --root={{ docroot_path }} dl registry_rebuild -y"
      delegate_to: "{{ delegate_host }}"
      register: drush_dl_result
      retries: 2
      until: drush_dl_result.rc == 0
      ignore_errors: yes
      #when: target_env == "staging" or target_env == "testint"

    - name: Output of Drush DL
      debug:
        var: drush_dl_result

    - name: Run Drush RR if Drupal 7
      command: /usr/bin/sudo su - apache -c "/usr/local/bin/drush --root={{ docroot_path }} rr"
    # command: /usr/local/bin/drush --alias-path=/data/aws_scripts/drush_aliases @{{ tenant }}.{{ target_env }} rr 
      delegate_to: "{{ delegate_host }}" 
      register: drush_rr_result
      retries: 3
      until: drush_rr_result.rc == 0

    - name: Output of Drush RR
      debug:
        var: drush_rr_result