---
- name: Show Job ID
  debug:
    msg: "{{ tower_job_id }}"

- name: Show email address
  debug:
    msg: "{{ email_address }}"

- name: Set empty Email Message
  set_fact:
    email_clear: []
    email_updb: []
    email_dl: []

- name: Email Message For PreTask Status
  set_fact:
    email_pretask: "{{ pretask_status }}"
    email_task: "{{ task_status }}"
    netstorage_message: ""


- name: Send Error Email
  mail:
    host: 10.0.10.87
    port: 25
    to:
      - <{{ email_address }}>
    from: esdowcmmonitoring@hq.dhs.gov
    subject: "Self-Service Database Refresh Results for Job: {{ tower_job_id }}"
    body: "{{ lookup('template', 'roles/aws_db_refresh/templates/email_error.j2') }}"
  when:
    - pretask_status == "Ansible Pre-Task Failed" or task_status == "FATAL - ERROR OCCURED CAUSING PLAYBOOK TO FAIL"

- name: Email When Netstorage Set as Target Env
  set_fact:
    email_netstorage: "{{ akamai_db_path }}/{{ sql_snap_file }}"
  when: 
    - task_status == "Ansible Task Finished Successfully"
    - target_env == "netstorage"

- name: Email Message for Drush DL Drupal 7
  set_fact:
    email_dl: "{{ email_dl + drush_dl_result.stderr_lines }}"
  when:
    - task_status == "Ansible Task Finished Successfully"
    - drupal_version == "7"
    - target_env == "staging" or target_env == "testint"
    - drush_dl_result is defined

- name: Email Message for Drush RR Drupal 7
  set_fact:
    email_clear: "{{ email_clear + drush_rr_result.stderr_lines }}"
  when:
    - task_status == "Ansible Task Finished Successfully"
    - drupal_version == "7"
    - target_env != "netstorage"


- name: Email Message for Drush UPDB D7
  set_fact:
    email_updb: "{{ email_updb + drush7_updb_result.stderr_lines }}"
  when:
    - task_status == "Ansible Task Finished Successfully"
    - drupal_version == "7"
    - target_env != "netstorage"

- name: Email Message for Drush CR Drupal 8
  set_fact:
    email_clear: "{{ email_clear + drush_cr_result.stderr_lines }}"
  when:
    - task_status == "Ansible Task Finished Successfully"
    - drupal_version == "8"
    - target_env != "netstorage"

- name: Email Message for Drush UPDB D8
  set_fact:
    email_updb: "{{ email_updb + drush_updb_result.stderr_lines }}"
  when:
    - task_status == "Ansible Task Finished Successfully"
    - drupal_version == "8"
    - target_env != "netstorage"


- name: Send an email
  mail:
    host: 10.0.10.87
    port: 25
    to:
      - <{{ email_address }}>
    from: esdowcmmonitoring@hq.dhs.gov
    subject: "Self-Service Database Refresh Results for Job: {{ tower_job_id }}"
    body: "{{ lookup('template', 'roles/aws_db_refresh/templates/email_body.j2') }}"
  when:
    - pretask_status == "OK"
    - task_status == "Ansible Task Finished Successfully"
    - email_address is defined