---
- hosts: "{{ ip_address }}"
  gather_facts: no
  become: yes
  become_method: sudo
  remote_user: ansible_tower
    
  environment:
    AWS_SHARED_CREDENTIALS_FILE: "/etc/aws/credentials"
    AWS_CONFIG_FILE: "/etc/aws/config"

  vars:
    ansible_host_key_checking: false

  roles:
    - aws_IAM_ec2
