---
- hosts: localhost
  become: yes
  become_method: sudo

  environment:
    AWS_SHARED_CREDENTIALS_FILE: "/etc/aws/credentials"
    AWS_CONFIG_FILE: "/etc/aws/config"
    PYTHONPATH: "/var/lib/aws/venv/aws/lib64/python3.6/site-packages/"
  
  vars:
    alarm_error: []
    efs_mount_command: "mount -t nfs -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,fsc"
    mgmt_prod_asset_mount: "production-assets.wcm.com:/"
    vpn_prod_asset_mount: "fs-d27eead3.efs.us-gov-west-1.amazonaws.com:/"
    mgmt_prod_asset_path: "/mnt/production/sites-files"
    mgmt_stage_asset_mount: "staging-assets.wcm.com:/"
    mgmt_stage_asset_path: "/mnt/staging/sites-files"
    mgmt_test_asset_mount: "testint-assets.wcm.com:/"
    mgmt_test_asset_path: "/mnt/testint/sites-files"
    web_asset_path: "/var/www/sites-files"
    web_asset_metric: "assetEFS-heartBeat"
    web_vhost_path: "/etc/httpd/conf.d"
    web_vhost_metric: "vhostEFS-heartBeat"
    
    

  pre_tasks:
    - include: roles/aws_create_alarms/pre_tasks/main.yml

  roles: 
    - aws_create_alarms