---
- hosts:  "{{ groups['tag_aws_autoscaling_groupName_'~env~'_as_group'] | random }}" 
  environment:
    AWS_SHARED_CREDENTIALS_FILE: "/etc/aws/credentials"
    AWS_CONFIG_FILE: "/etc/aws/config"
    PYTHONPATH: "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/"

  roles:
    - aws_drushcron

  #remote_user: ansible_tower
  become: yes
  become_user: ansible_tower
  become_method: sudo
