---
- hosts: tag_tower_managed_true
  gather_facts: no
  remote_user: ansible_tower
  become: yes
  become_method: sudo

  environment:
    AWS_SHARED_CREDENTIALS_FILE: "/etc/aws/credentials"
    AWS_CONFIG_FILE: "/etc/aws/config"
    PYTHONPATH: "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/"

  roles:
    - aws_manage_tower_access