---
- hosts: "all_testint_webheads[0]"
  become: yes
  become_method: sudo
  remote_user: bamboo

  vars:
    formversions: ['7001','7003']
    demo_sitefiles: 'testint.caadi_gov_build'
    testint_sitefiles: 'testint.dhs_gov_build'
    staging_sitefiles: 'staging.dhs_gov_build'
    prod_sitefiles: 'dhs_gov_build'
    formpath: '/var/www/sites-files/{{ vars[env+"_sitefiles"] }}/files-private/webform/CAADI_{{ formversion }}/{{ formversion }}FormSubmissions'
    rsync_crontime_7001: '*/2'
    rsync_crontime_7003: '*/3'
    error_crontime_7001: ['*', '*/4']
    error_crontime_7003: ['2', '*/4']
    #Note that this is set to run every 1 hour instead of 4 in prod, modify this time inside of the cronjob check tasks of the caadi_cleanup role 

  pre_tasks:

    - name: "Get Yesterday's date"
      shell: 'date +%Y%m%d -d "{{ days_ago | default(1) }} day ago"'
      register: yesterday

    - name: "Caadi Cleanup"
      debug:
        msg: "When Caadi forms are submitted to our server, their directory is rsync'd to the destination server and, if that is successful, the contents of their directories are removed from our server.  This playbook logs the emptied directories from yestserday's successful rsyncs and removes them, then organizes yesterday's rsync logs. The intent is to record what was done yesterday ({{ yesterday.stdout[4] }}{{ yesterday.stdout[5] }}/{{ yesterday.stdout[6] }}{{ yesterday.stdout[7] }}/{{ yesterday.stdout[:4] }}) without interfering with the submissions or logs of the current day. This can be run for any number of days before today by including the variable 'days_ago' equal to the desired number; default is 1."
    - name: "Verify Paths" 
      debug:
        msg: "Also please ensure you've provided the correct formpath: {{ formpath }} and environment: {{ env }}. Note that if CAADI has gone live and the environment says 'demo', you need to remove this variable from the job template 'extra variables' section in ansible tower, so that it can be picked up from the hosts' group_vars."
      vars:
        formversion: '{{ formversion }}'
      loop: '{{ formversions }}'
      loop_control:
        loop_var: formversion

  tasks:
    - name: "Include CAADI role"
      include_role:
        name: caadi_cleanup
      vars:
        formversion: '{{ formversion }}'
      loop: '{{ formversions }}'
      loop_control: 
        loop_var: formversion




    
