---
- name: installing splunk forwarder to EC2 instances
<<<<<<< HEAD
  hosts: splunk
  remote_user: ansible_tower
  become: True
=======
  hosts: tag_tower_managed_true,!tag_Purpose_Logging
  remote_user: ansible_tower
  become: yes
  become_method: sudo
>>>>>>> 5fd3b90671d556ff969207e404c5c7c37dafbdf1

  vars: 
    splunk_forwarder_user: splunk
    splunk_forwarder_group: splunk
    splunk_working_directory: '/tmp/splunk'
<<<<<<< HEAD
    splunk_index_server: 10.0.4.97
    splunk_indexer_server_port: '9997'
=======
    splunk_index_server: 10.0.10.42
    splunk_indexer_server_port: '9997'
    splunk_deployment_server_port: '8089'
>>>>>>> 5fd3b90671d556ff969207e404c5c7c37dafbdf1
    splunk_password: 'Password'
    splunk_release_version: "splunkforwarder-8.0.1-6db836e2fb9e-linux-2.6-x86_64.rpm"
    splunk_package: "http://download.splunk.com/releases/8.0.1/universalforwarder/linux/splunkforwarder-8.0.1-6db836e2fb9e-linux-2.6-x86_64.rpm"

  roles: 
    - splunk-forwarder
